### ISSUE TITLE
spacing issue + underlining issue

### ISSUE THREAD

**Issue by clayshieh** [su1ts/startpages#1]
This is for statepage-boxes.html, .main's left attribute should be 16% not 18% bc (100%-68%)/2 = 16% I was going crazy because I couldn't figure out why it wasn't centered. 

Also for some reason the li a links are underlined for me still so I had to change that part of the code too.

Thanks for the startpage though!

**Comment by jltk** [comment]
Kudos for your comment (note to self: check issues in own repos).

Bummer you had so much trouble with that old startpage of mine! It was very poorly written.

I fixed all those issues in my newest commit (https://github.com/jnsltk/startpages/blob/master/startpage-boxes.html).

Have a nice weekend :ok_hand:
